### ISSUE TITLE
Creating information

### ISSUE THREAD

**Issue by amirbelder** [qiminchen/UNIST#1]
Hi,
You have an amazing paper and awesome results!
As I may wish to check the results on other datasets, could you please share how you create your hdf5 files of the datasets?

Thanks!
Amir

**Comment by qiminchen** [comment]
Hi, thanks for your interest in the paper. I will update the data process on README today and let you know

**Comment by qiminchen** [comment]
@amirbelder I updated the README 2d sampling code can be found in [here](https://github.com/qiminchen/UNIST/blob/2178f34b59a9e81d7a8ff27957216283d31118c1/sampling.py) and 3d sampling code can be found [here](https://github.com/czq142857/IM-NET/tree/master/point_sampling), please let me know if you have any questions
