### ISSUE TITLE
Table. 3 in paper  (one-sided CD)

### ISSUE THREAD

**Issue by Yunyung** [qiminchen/UNIST#2]
Hi,
First, thank you for sharing this awesome project!  However, I encountered one issue about reproducing the one-sided CD experiment (Table. 3).

I'm trying two chamfer distance implementations(1. https://github.com/chrdiller/pyTorchChamferDistance, 
2. https://kaolin.readthedocs.io/en/latest/modules/kaolin.metrics.pointcloud.html#kaolin.metrics.pointcloud.sided_distance), but the result of my implementations are much smaller (about 10x) than reported values in Table. 3.
(e.g.

| | w Arm → w/o Arm | w/o Arm → w Arm |
| :-----| ----: | ----: |
| LOGAN (My implementation) | 0.0010 | 0.0016 |
| LOGAN (Paper) | 0.0249 | 0.0273 |

)

Could you share the implementation or hint some resources for us? 

Again, thank you for your great efforts!

Cheers,
Yung

**Comment by qiminchen** [comment]
Hi, thank you for your interest in our paper, we use the implementation here to compute one-sided CD
https://github.com/czq142857/NMC/blob/d111c66101223df4e7af6c84b4a0d22d733b725b/eval_cd_nc_f1_ecd_ef1.py#L54

**Comment by Yunyung** [comment]
Thank you for your quick response! I gain a deeper understanding of how to compute one-sided CD through the function you provided

I want to confirm  that the inputs of LOGAN is also sampling from mesh during one-sided CD experiment rather than dataset provided in LOGAN repository (https://github.com/kangxue/LOGAN). Because the dataset provided by LOGAN is point cloud format instead of mesh.
Is my understanding correct? 
 
Cheers,
Yung

**Comment by qiminchen** [comment]
yes, so make sure the point cloud coordinate of LOGAN data is consistent with your own data

**Comment by Yunyung** [comment]
Thank you for your reply. I still have a hard time when reproducing this experiment. 

1. The LOGAN is trained from the data sampling from mesh or the dataset provided in LOGAN repository?  

2. (https://github.com/czq142857/NMC/blob/d111c66101223df4e7af6c84b4a0d22d733b725b/eval_cd_nc_f1_ecd_ef1.py#L54) CD in this function is computed from two point cloud sampling from mesh, but the output of LOGAN is point cloud format.
That is to say,  to calculate LOGAN's one-sided CD, we must translate the output of LOGAN(point cloud) to mesh as described in section6.5 of supplementary material.
Is my understanding correct? 

Or would you mind releasing related code or explaining more details? 

Thank you. I appreciate it.
Yung

**Comment by qiminchen** [comment]
Hi, sorry I didnt make this clear.
1. LOGAN is trained directly from the data provided in LOGAN repository
2. supplementary section 6.5 has nothing to do with one-sided CD, the code for computing CD in NMC takes two point cloud sampling from mesh, however the output of LOGAN is already point cloud, so you can compute CD directly on LOGAN's output, no need to convert point cloud to mesh and sample point cloud again, this does not make sense.

please let me know if you have any questions.

**Comment by Yunyung** [comment]
Thank you for your time and help. I thought i had understood how one-sided CD calculated via your help.

I have one more question about the reported value of one-sided CD in paper .

From my perspective, the CD value should be lower than the value of paper. For example, the CD value of table 1. in IM-NET (https://arxiv.org/abs/1812.02822) is 4 decimal places (about 0.0003~0.0012) and NMC (https://arxiv.org/abs/2106.11272) is 5 decimal places, but one-sided CD in paper is 2 decimal places. 

In my opinion, even though transformation task (armchair-armlesschair) may have a larger CD value than reconstruction task, about 100x times seems a little bit strange? Or did I miss something? 

Cheers,
Yung
