### ISSUE TITLE
Other 3D pretrained models

### ISSUE THREAD

**Issue by XLechter** [qiminchen/UNIST#5]
Hi, thanks for your great work. I wonder if you could kindly release the pre-trained models for talltable-shorttable and armchair-armless chair used in your 3D experiments? Thank you so much!

**Comment by qiminchen** [comment]
Hi @XLechter, I updated the google drive so you can find the pre-trained model weights now, please let me know if you have any questions.

**Comment by XLechter** [comment]
> Hi @XLechter, I updated the google drive so you can find the pre-trained model weights now, please let me know if you have any questions.

Well received. It works well. Thank you so much.

**Comment by XLechter** [comment]
Hi @qiminchen , sorry for bothering you again. May I ask if you have the testing resutls of LOGAN for talltable-shorttable, armchair-armless chair, chair-table?   I found the TensorFlow operator in LOGAN cannot be compiled with CUDA 11.

**Comment by qiminchen** [comment]
Hi @XLechter, I updated the google drive, you can now find the LOGAN test results under the checkpoint folder, please do kindly acknowledge Kangxue Yin, the author of LOGAN if you find this helpful! Thank you.

**Comment by XLechter** [comment]
@qiminchen Well received. Thank you so much for your help. I will also acknowledge Kangxue Yin.
